apiVersion: ai.sap.com/v1alpha1
kind: Deployment
metadata:
  name: chatbot-deployment   # unique deployment name
  annotations:
    scenarios.ai.sap.com/name: chatbot-scenario   # scenario ID
    executables.ai.sap.com/name: chatbot-executable # executable ID
spec:
  template:
    spec:
      containers:
        - name: chatbot-container
          image: docker.io/your-dockerhub-username/sustainability-chatbot:latest
          command: ["python", "app.py"]   # entrypoint command
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "1"
              memory: "2Gi"
          env:
            - name: MODEL_NAME
              value: "google/flan-t5-small"   # example custom model
