apiVersion: apps/v1
kind: Deployment
metadata:
  name: sustainability-chatbo-deploy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sustainability-chatbo
  template:
    metadata:
      labels:
        app: sustainability-chatbo
    spec:
      containers:
        - name: sustainability-chatbo
          image: akshay1p1/sustainability-chatbo:latest
          ports:
            - containerPort: 8000
          env:
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_URL
            - name: SUPABASE_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secret
                  key: SUPABASE_KEY
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: GEMINI_API_KEY
