apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: sustainability-chatbot-serving
  annotations:
    scenarios.ai.sap.com/name: "sustainability-chatbot-scenario"
    scenarios.ai.sap.com/description: "Sustainability Chatbot scenario"
    executables.ai.sap.com/name: "sustainability-chatbot-executable"
    executables.ai.sap.com/description: "Deploys Sustainability Chatbot container"
  labels:
    ai.sap.com/version: "1.0.0"
    scenarios.ai.sap.com/id: "sustainability-chatbot-scenario"
spec:
  inputs:
    parameters:
      - name: image
        type: string
        default: "docker.io/akshay1p1/sustainability-chatbot:latest"
        description: "Docker image for sustainability chatbot"
      - name: resourceGroup
        type: string
        default: "default"
        description: "Resource group for deployment"
    artifacts: []
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: rps
        autoscaling.knative.dev/target: 100
        autoscaling.knative.dev/targetBurstCapacity: 70
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        imagePullSecrets:
          - name: dockerhub-secret
        containers:
          - name: kserve-container
            image: "{{inputs.parameters.image}}"
            ports:
              - containerPort: 5000
                protocol: TCP
            env:
              - name: SUPABASE_URL
                valueFrom:
                  secretKeyRef:
                    name: supabase-secret
                    key: SUPABASE_URL
              - name: SUPABASE_KEY
                valueFrom:
                  secretKeyRef:
                    name: supabase-secret
                    key: SUPABASE_KEY
              - name: GEMINI_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: gemini-secret
                    key: GEMINI_API_KEY