name: Build & Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2) Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest .

      # 4) Push Docker image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest

      # 5) Output image information
      - name: Print image details
        run: |
          echo "=============================================="
          echo " DOCKER IMAGE BUILT AND PUSHED"
          echo "=============================================="
          echo "Image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest"
          echo "=============================================="
          echo "Next steps:"
          echo "1. Go to SAP AI Core Launchpad"
          echo "2. Create/update your deployment configuration"
          echo "3. Use the image URL above"
          echo "4. Deploy manually"
          echo "=============================================="