name: Build & Validate SAP AI Core

on:
  push:
    branches:
      - main

jobs:
  build-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest

    - name: Install tools
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        pip install --user ai-core-sdk

    - name: Get AI Core OAuth Token
      id: get_token
      env:
        AUTH_URL: ${{ secrets.AUTH_URL }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      run: |
        response=$(curl -s -X POST "$AUTH_URL" \
          -H "Content-Type: application/x-www-form-urlencoded" \
          -d "grant_type=client_credentials&client_id=$CLIENT_ID&client_secret=$CLIENT_SECRET")
        echo "$response" | jq .
        token=$(echo "$response" | jq -r '.access_token')
        if [ -z "$token" ] || [ "$token" = "null" ]; then
          echo "Failed to get access_token from AUTH_URL"; exit 1;
        fi
        echo "AICORE_TOKEN=$token" >> $GITHUB_ENV

    - name: Validate AI Core API connectivity
      env:
        AI_API_URL: ${{ secrets.AI_API_URL }}
        AICORE_TOKEN: ${{ env.AICORE_TOKEN }}
      run: |
        echo "Listing resource groups to validate connectivity..."
        curl -s -H "Authorization: Bearer $AICORE_TOKEN" \
             -H "AI-Resource-Group: default" \
             "$AI_API_URL/v2/resourceGroups" | jq .
        echo "Success. Your creds and API URL are valid."

    - name: Print image URL for Launchpad
      run: |
        echo "Container image to use in Serving Template:"
        echo "docker.io/${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbot:latest"
