name: Build & Deploy to SAP AI Core

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    # Checkout repo
    - name: Checkout repo
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Log in to DockerHub
    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest .

    # Push Docker image
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/sustainability-chatbo:latest

    # Install AI Core CLI
    - name: Install AI Core CLI
      run: |
        # Download the AI Core CLI from SAP's repository
        curl -LO https://github.com/SAP/ai-core-sdk/releases/latest/download/ai-core-cli-linux-amd64
        chmod +x ai-core-cli-linux-amd64
        sudo mv ai-core-cli-linux-amd64 /usr/local/bin/aicore
        aicore version

    # Create secrets in AI Core
    - name: Create Supabase Secret in AI Core
      run: |
        aicore secret create \
          --name supabase-secret \
          --data SUPABASE_URL=${{ secrets.SUPABASE_URL }} \
          --data SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} \
          --label "ai.sap.com/resourcePlan=free"

    - name: Create Gemini Secret in AI Core
      run: |
        aicore secret create \
          --name gemini-secret \
          --data GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }} \
          --label "ai.sap.com/resourcePlan=free"

    # Create Docker registry secret
    - name: Create Docker Registry Secret
      run: |
        aicore secret create \
          --name docker-registry-secret \
          --type kubernetes.io/dockerconfigjson \
          --docker-server https://index.docker.io/v1/ \
          --docker-username ${{ secrets.DOCKERHUB_USERNAME }} \
          --docker-password ${{ secrets.DOCKERHUB_TOKEN }} \
          --label "ai.sap.com/resourcePlan=free"

    # Login to AI Core
    - name: Login to AI Core
      run: |
        aicore login \
          --url "${{ secrets.AI_API_URL }}" \
          --clientid "${{ secrets.CLIENT_ID }}" \
          --clientsecret "${{ secrets.CLIENT_SECRET }}" \
          --tokenurl "${{ secrets.AUTH_URL }}"

    # Push Workflow Template
    - name: Push Workflow Template
      run: |
        aicore workflow push -f sap_ai_core_deployment.yaml

    # Create Deployment
    - name: Create Deployment
      run: |
        aicore deployment create -f sap_ai_core_deployment.yaml

    # Get Deployment URL
    - name: Get Deployment URL
      run: |
        echo "Deployment status:"
        aicore deployment list
        echo -e "\nTo get the service URL, run: aicore service list"